// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/core/v1/health.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthServiceCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthServiceCheckRequest) Reset() {
	*x = HealthServiceCheckRequest{}
	mi := &file_api_core_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthServiceCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthServiceCheckRequest) ProtoMessage() {}

func (x *HealthServiceCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_core_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthServiceCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthServiceCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_core_v1_health_proto_rawDescGZIP(), []int{0}
}

type HealthServiceCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthServiceCheckResponse) Reset() {
	*x = HealthServiceCheckResponse{}
	mi := &file_api_core_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthServiceCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthServiceCheckResponse) ProtoMessage() {}

func (x *HealthServiceCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_core_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthServiceCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthServiceCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_core_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthServiceCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthServiceCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_core_v1_health_proto protoreflect.FileDescriptor

const file_api_core_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x18api/core/v1/health.proto\x12\vapi.core.v1\"\x1b\n" +
	"\x19HealthServiceCheckRequest\"N\n" +
	"\x1aHealthServiceCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2i\n" +
	"\rHealthService\x12X\n" +
	"\x05Check\x12&.api.core.v1.HealthServiceCheckRequest\x1a'.api.core.v1.HealthServiceCheckResponseB\x9e\x01\n" +
	"\x0fcom.api.core.v1B\vHealthProtoP\x01Z0github.com/hyp3rd/starter/pkg/api/core/v1;corev1\xa2\x02\x03ACX\xaa\x02\vApi.Core.V1\xca\x02\vApi\\Core\\V1\xe2\x02\x17Api\\Core\\V1\\GPBMetadata\xea\x02\rApi::Core::V1b\x06proto3"

var (
	file_api_core_v1_health_proto_rawDescOnce sync.Once
	file_api_core_v1_health_proto_rawDescData []byte
)

func file_api_core_v1_health_proto_rawDescGZIP() []byte {
	file_api_core_v1_health_proto_rawDescOnce.Do(func() {
		file_api_core_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_core_v1_health_proto_rawDesc), len(file_api_core_v1_health_proto_rawDesc)))
	})
	return file_api_core_v1_health_proto_rawDescData
}

var file_api_core_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_core_v1_health_proto_goTypes = []any{
	(*HealthServiceCheckRequest)(nil),  // 0: api.core.v1.HealthServiceCheckRequest
	(*HealthServiceCheckResponse)(nil), // 1: api.core.v1.HealthServiceCheckResponse
}
var file_api_core_v1_health_proto_depIdxs = []int32{
	0, // 0: api.core.v1.HealthService.Check:input_type -> api.core.v1.HealthServiceCheckRequest
	1, // 1: api.core.v1.HealthService.Check:output_type -> api.core.v1.HealthServiceCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_core_v1_health_proto_init() }
func file_api_core_v1_health_proto_init() {
	if File_api_core_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_core_v1_health_proto_rawDesc), len(file_api_core_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_core_v1_health_proto_goTypes,
		DependencyIndexes: file_api_core_v1_health_proto_depIdxs,
		MessageInfos:      file_api_core_v1_health_proto_msgTypes,
	}.Build()
	File_api_core_v1_health_proto = out.File
	file_api_core_v1_health_proto_goTypes = nil
	file_api_core_v1_health_proto_depIdxs = nil
}
